# Generated by Django 5.0.3 on 2024-04-12 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_ourinstagramstory_story_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourinstagramstory',
            name='story_link',
            field=models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Story Link'),
        ),
    ]
