# Generated by Django 4.2.11 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifictionotp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
